language: objective-c
osx_image: xcode7.2

# Set up our rubygems (slather and xcpretty, namely)
install: 
 - gem install xcpretty slather -N
 
before_script:
# Start by nuking any lingering codecov files. These can cause issues when the xcode version changes
  - find . -name "*.gcda" -print0 | xargs -0 rm



# Tell the shell to echo failure codes up the pipe so that Travis will properly fail the
# build when the xcodebuild command fails
  - set -o pipefail
  
  #- brew cask uninstall oclint
  - brew tap oclint/formulae
  - brew install oclint
  #- brew update
  #- brew install infer
  #- brew install oclint

script:  
# Build and Test the ADALiOS library
#  - build/iOS_Static_Lib
  
# Build the Test App (to make sure it doesn't break
#  - build/iOS_Test_App
  
# Build and Test ADAL for Mac
#  - build/Mac_Framework
  
# Build Mac Test App
#  - build/Mac_Test_App

# Test ADAL for Mac 32-bit
  - build/Mac_32_bit

# Analyse the ADALiOS library
#  - build/Analyze_iOS_Static_Lib

after_success:
# Run slather once to have it print out the results in the travis log
#  - slather coverage -s ADAL/ADAL.xcodeproj

notifications:
  slack:
    secure: BIziStN+8QJLjdqNbLyRWWw9kI/MQsX+rZq+xz/bfTANk0gbEryLgMSiEoHxdoctu0dOqOet1voYuDKs3RQW3W0yh0AhDwVgWThNkTA0oDXF8zqm9AXettXNtmYHipaYb6+z6L4lpJOkClQp3hAheu8cM2igqye1O0FQla9g/PA=

